// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Entities;

public partial class Country
{
    public int CountryId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Event> Event { get; set; } = new List<Event>();
}