// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Entities;

public partial class Event
{
    public int EventId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Era { get; set; }

    public int Year { get; set; }

    public int TimelineId { get; set; }

    public bool IsReviewed { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsApproved { get; set; }

    public int? ReviewerUserId { get; set; }

    public DateTime? ReviewDate { get; set; }

    public int CreatorUserId { get; set; }

    public DateTime CreateDate { get; set; }

    public int? ApproverUserId { get; set; }

    public DateTime? ApproveDate { get; set; }

    public DateTime? LastUpdateDate { get; set; }

    public int? LastUpdaterUserId { get; set; }

    public DateTime? EventDate { get; set; }

    public int CountryId { get; set; }

    public virtual User ApproverUser { get; set; }

    public virtual Country Country { get; set; }

    public virtual User CreatorUser { get; set; }

    public virtual ICollection<Image> Image { get; set; } = new List<Image>();

    public virtual User LastUpdaterUser { get; set; }

    public virtual ICollection<Reference> Reference { get; set; } = new List<Reference>();

    public virtual User ReviewerUser { get; set; }

    public virtual Timeline Timeline { get; set; }
}