// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Entities;

public partial class Event_Tag
{
    public int TagId { get; set; }

    public int? EventId { get; set; }

    public virtual Event Event { get; set; }

    public virtual Tag Tag { get; set; }
}