// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Entities;

public partial class Reference
{
    public int ReferenceId { get; set; }

    public int EventId { get; set; }

    public string Url { get; set; }

    public virtual Event Event { get; set; }
}