// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Entities;

public partial class Tag
{
    public int TagId { get; set; }

    public string Name { get; set; }

    public bool IsDeleted { get; set; }
}