// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Data.Entities;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Data.Entities
{
    public partial class TimelinesDbContext
    {
        private ITimelinesDbContextProcedures _procedures;

        public virtual ITimelinesDbContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new TimelinesDbContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public ITimelinesDbContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
        }
    }

    public partial class TimelinesDbContextProcedures : ITimelinesDbContextProcedures
    {
        private readonly TimelinesDbContext _context;

        public TimelinesDbContextProcedures(TimelinesDbContext context)
        {
            _context = context;
        }
    }
}
