// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Entities;

public partial class User
{
    public int UserId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Middle_Name { get; set; }

    public string Email { get; set; }

    public string UserPrincipalName { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<Event> EventApproverUser { get; set; } = new List<Event>();

    public virtual ICollection<Event> EventCreatorUser { get; set; } = new List<Event>();

    public virtual ICollection<Event> EventLastUpdaterUser { get; set; } = new List<Event>();

    public virtual ICollection<Event> EventReviewerUser { get; set; } = new List<Event>();
}