// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Data.Entities.Configurations
{
    public partial class Event_TagConfiguration : IEntityTypeConfiguration<Event_Tag>
    {
        public void Configure(EntityTypeBuilder<Event_Tag> entity)
        {
            entity.HasNoKey();

            entity.HasOne(d => d.Event).WithMany()
            .HasForeignKey(d => d.EventId)
            .HasConstraintName("FK_Event_Tag_Event");

            entity.HasOne(d => d.Tag).WithMany()
            .HasForeignKey(d => d.TagId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Event_Tag_Tag");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Event_Tag> entity);
    }
}
