// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Data.Entities.Configurations
{
    public partial class EventConfiguration : IEntityTypeConfiguration<Event>
    {
        public void Configure(EntityTypeBuilder<Event> entity)
        {
            entity.HasIndex(e => new { e.Title, e.CountryId, e.Era }, "UC_Event").IsUnique();

            entity.Property(e => e.ApproveDate).HasColumnType("date");
            entity.Property(e => e.CreateDate).HasColumnType("date");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.Era)
            .IsRequired()
            .HasMaxLength(10);
            entity.Property(e => e.EventDate).HasColumnType("date");
            entity.Property(e => e.LastUpdateDate).HasColumnType("date");
            entity.Property(e => e.ReviewDate).HasColumnType("date");
            entity.Property(e => e.Title)
            .IsRequired()
            .HasMaxLength(150);

            entity.HasOne(d => d.ApproverUser).WithMany(p => p.EventApproverUser).HasForeignKey(d => d.ApproverUserId);

            entity.HasOne(d => d.Country).WithMany(p => p.Event)
            .HasForeignKey(d => d.CountryId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Event_Country");

            entity.HasOne(d => d.CreatorUser).WithMany(p => p.EventCreatorUser)
            .HasForeignKey(d => d.CreatorUserId)
            .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.LastUpdaterUser).WithMany(p => p.EventLastUpdaterUser).HasForeignKey(d => d.LastUpdaterUserId);

            entity.HasOne(d => d.ReviewerUser).WithMany(p => p.EventReviewerUser).HasForeignKey(d => d.ReviewerUserId);

            entity.HasOne(d => d.Timeline).WithMany(p => p.Event)
            .HasForeignKey(d => d.TimelineId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Event_Timeline");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Event> entity);
    }
}
