// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Data.Entities.Configurations
{
    public partial class TimelineConfiguration : IEntityTypeConfiguration<Timeline>
    {
        public void Configure(EntityTypeBuilder<Timeline> entity)
        {
            entity.HasIndex(e => new { e.Era, e.CenturyId }, "UC_Timeline").IsUnique();

            entity.Property(e => e.Era)
            .IsRequired()
            .HasMaxLength(10);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Timeline> entity);
    }
}
