// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Data.Entities.Configurations
{
    public partial class UserConfiguration : IEntityTypeConfiguration<User>
    {
        public void Configure(EntityTypeBuilder<User> entity)
        {
            entity.Property(e => e.Email)
            .IsRequired()
            .HasMaxLength(30);
            entity.Property(e => e.FirstName)
            .IsRequired()
            .HasMaxLength(20);
            entity.Property(e => e.LastName)
            .IsRequired()
            .HasMaxLength(20);
            entity.Property(e => e.Middle_Name)
            .HasMaxLength(20)
            .HasColumnName("Middle Name");
            entity.Property(e => e.UserPrincipalName)
            .HasMaxLength(60)
            .IsFixedLength();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<User> entity);
    }
}
